blank_issues_enabled: false
contact_links:
  - name: ğŸ¤·ğŸ’»ğŸ¤¦ Question/Forum
    url: https://framacolibri.org/c/retro3
    about: You can ask and answer other questions here
  - name: ğŸ’¬ Matrix
    url: https://matrix.to/#/#retro3:matrix.org
    about: Chat with us via Matrix for quick Q/A here
  - name: ğŸ’¬ IRC
    url: https://web.libera.chat/#retro3
    about: Chat with us via IRC for quick Q/A here
